### ISSUE TITLE
Please add license

### ISSUE THREAD

**Issue by daisukeokaoss** [mofas/mindMap#1]
It is very good app. I am very impressed.But License is not added.
Please add license.
Preferred License is MIT License.
but other license is OK
I want to improve this app.

**Comment by up9cloud** [comment]
@mofas 大大，可以放個 license 嗎？很棒的作品。

**Comment by mofas** [comment]
Sorry, I don't pay attention to this project for a long time.

I have added the MIT LICENSE to it, thanks for notifying me.

33a6b355cba439977515a0cd2bf0e7320f6c9c89
